services:
  db2:
    image: postgres:15
    environment:
      POSTGRES_DB: squid2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
    shm_size: 1gb
